name: CMake
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Load submodules
      run: chmod +x ./scripts/update_components.sh && ./scripts/update_components.sh 
    - name: Lint
      uses: cpp-linter/cpp-linter-action@v1
        id: linter

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32
        path: '.'
